include_guard(GLOBAL)

function(project_name_validate_sanitizers)
  if(PROJECT_ENABLE_TSAN AND (PROJECT_ENABLE_ASAN OR PROJECT_ENABLE_MSAN))
    message(FATAL_ERROR "TSan cannot be combined with ASan or MSan.")
  endif()
  if(PROJECT_ENABLE_MSAN AND (PROJECT_ENABLE_ASAN OR PROJECT_ENABLE_UBSAN))
    message(FATAL_ERROR "MSan is isolated and cannot be combined with ASan or UBSan.")
  endif()
endfunction()

function(project_name_enable_sanitizers target)
  if(MSVC)
    return()
  endif()
  set(flags)
  if(PROJECT_ENABLE_ASAN)
    list(APPEND flags address)
  endif()
  if(PROJECT_ENABLE_UBSAN)
    list(APPEND flags undefined)
  endif()
  if(PROJECT_ENABLE_TSAN)
    list(APPEND flags thread)
  endif()
  if(PROJECT_ENABLE_MSAN)
    list(APPEND flags memory)
  endif()
  if(flags)
    string(JOIN "," sanitizer_list ${flags})
    target_compile_options(${target} PRIVATE "-fsanitize=${sanitizer_list}" -fno-omit-frame-pointer)
    target_link_options(${target} PRIVATE "-fsanitize=${sanitizer_list}")
  endif()
endfunction()
